Repository pymssql/pymssql, pull requests merged in 2018-08, with the labels that each got.

#568 Appveyor build artifact fix
  appveyor.yml
Labels: Blocked: FreeTDS, build

#573 Set version to RC.
  src/version.h
Labels: release

#577 manylinux build script
  dev/build_wheels.sh
  src/version.h
Labels: build

#583 Test adding Python 3.7 to Windows build.
  .circleci/config.yml
  appveyor.yml
  dev/build_manylinux_wheels.sh
  dev/test_manylinux_wheels.sh
Labels: build

#587 2.1.4
  .circleci/config.yml
  .gitignore
  ChangeLog
  ChangeLog_highlights.rst
  appveyor.yml
  setup.py
  src/version.h
Labels: release

#592 Change collections import to collections.abc to fix deprecation warnings
  src/_mssql.pyx
Labels: internals
